quarkus:
  log:
    level: INFO
  http:
    cors:
      ~: true
    port: 8123
  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3306/utk_admin_perpus
  hibernate-orm:
    database:
      generation:
        ~: none